name: food_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  navigation:
    path: ./navigation
  welcome:
    path: ./features/welcome
  settings:
    path: ./features/settings
  data:
    path: ./data
  core:
    path: ./core
  core_ui:
    path: ./core_ui/
  domain:
    path: ./domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
